version: '3.9'

services:
  doom-emacs:
    image: ghcr.io/jabuxas/docker-emacs:master
    container_name: doom-session
    
    stdin_open: true
    tty: true
    network_mode: "host"
    user: "1001:1001"
    
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      
      - ./doom:/home/dev/.config/doom
      
      - ${HOME}:/home/dev/work
